name: LeetCode Sync

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Python submissions
      - name: Sync Python solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          language: python
          folder: solutions/Python

      # SQL submissions
      - name: Sync SQL solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          language: sql
          folder: solutions/SQL

      # Java submissions
      - name: Sync Java solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          language: java
          folder: solutions/Java

      # C++ submissions
      - name: Sync C++ solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          language: cpp
          folder: solutions/Cpp

      # 🛠 Fix misplaced SQL files (if action ignores folder)
      - name: Fix misplaced SQL files
        run: |
          mkdir -p solutions/SQL
          shopt -s nullglob
          for f in *.sql; do
            mv "$f" solutions/SQL/
          done
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add solutions/SQL/*.sql || true
          git commit -m "Move SQL submissions into solutions/SQL" || echo "No misplaced SQL files"
          git push
