name: LeetCode Sync

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Sync all LeetCode submissions
      - name: Sync All LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          destination-folder: solutions
          verbose: true

      # Step 3: Organize submissions into language folders
      - name: Organize Submissions by Language
        run: |
          mkdir -p solutions/Python solutions/SQL solutions/Java solutions/Cpp

          # Move files based on extensions
          shopt -s nullglob
          for f in solutions/*.py; do mv "$f" solutions/Python/; done
          for f in solutions/*.java; do mv "$f" solutions/Java/; done
          for f in solutions/*.cpp; do mv "$f" solutions/Cpp/; done
          for f in solutions/*.sql; do mv "$f" solutions/SQL/; done

          # Detect SQL submissions without extensions
          for f in solutions/*; do
            if [[ -f "$f" && ! "$f" =~ \.py|\.java|\.cpp|\.sql ]]; then
              if grep -iqE "SELECT|UPDATE|INSERT|DELETE|FROM|WHERE" "$f"; then
                mv "$f" solutions/SQL/
              fi
            fi
          done

          # Commit and push changes
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add solutions/*
          git commit -m "Organize LeetCode submissions by language" || echo "No new files to organize"
          git push
